---
title: "R script"
author: "Frank Liang"
date: "19/05/2021"
output: html_document
---

```{r}
install.packages("rnoaa")
install.packages("ncdf4")
```

```{r}
library(rnoaa)
library(leaflet)
```

`lcd` let you view temprature over year in one particular location
```{r}
x <- lcd(station = "01338099999", year = 2015)
class(x)
View(x)
```

```{r}
argo_search("coord", yearmin = 2007, yearmax = 2009)
```

```{r}
ghcnd_stations(lattitude = 53.4808 , longitude = -2.2426, first_year = 2015, last_year = 2020)
```


```{r}
# look up all stations
#see all stations 
isd_stations(refresh = FALSE) %>%
  View()
```

```{r}
# station in machester
isd_stations_search(lat = 53.4808 , lon = -2.2426, radius = 15) %>%
  select( c(station_name, lat, lon)) -> df

df
```

```{r}
uk_lon <- 0
uk_lat <- 55.3781

leaflet(df) %>%
  setView(lng = uk_lon, lat = uk_lat, zoom = 5) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%
  addMarkers(
    popup = ~station_name
  )

```

```{r}
# station in South China
cor <- c(30.566667, 114.266667)

isd_stations_search(lat = cor[1], lon = cor[2], radius = 30) %>%
  select( c(station_name, lat, lon)) -> df

leaflet(df) %>%
  setView(lat = cor[1], lng = cor[2], zoom = 5) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%
  addMarkers(
    popup = ~station_name
  )
```

```{r}
coops_search(station_name = "MANCHESTER/BARTON", product = "humidity")
```

```{r}
cor <- c(53.4808, -2.2426)

isd_stations_search(lat = cor[1], lon = cor[2], radius = 30) %>%
  select( c(station_name, lat, lon)) -> df

leaflet(df) %>%
  setView(lat = cor[1], lng = cor[2], zoom = 5) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%
  addMarkers(
    popup = ~station_name
  )
```

